// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGpsojkc-4U0EMZMIKs4r625TvZ5ybE18',
    appId: '1:170917901787:web:8d95ed4080c942417ee3fe',
    messagingSenderId: '170917901787',
    projectId: 'saude-facil-inovatech-13462',
    authDomain: 'saude-facil-inovatech-13462.firebaseapp.com',
    storageBucket: 'saude-facil-inovatech-13462.firebasestorage.app',
    measurementId: 'G-C60FRVQ7XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmjlbS7ooT8pvkd13B9AVrfgGrGSveD_Q',
    appId: '1:170917901787:android:58c45e6c1ed9edef7ee3fe',
    messagingSenderId: '170917901787',
    projectId: 'saude-facil-inovatech-13462',
    storageBucket: 'saude-facil-inovatech-13462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLWtSkGGaSyjdXVMKtFbTFpmh8dNq6QsA',
    appId: '1:170917901787:ios:c5ee29c765c2b5027ee3fe',
    messagingSenderId: '170917901787',
    projectId: 'saude-facil-inovatech-13462',
    storageBucket: 'saude-facil-inovatech-13462.firebasestorage.app',
    iosBundleId: 'com.example.saudeFacilInovatech',
  );
}
